# Site settings
title: Matthew Archer
email: ma595@cam.ac.uk
description: "Matthew Archer"
url: "http://www.mattarcher.co.uk"
# twitter_username: js947
github_username:  mjArcher

# Build settings
markdown: kramdown
permalink: pretty
